# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[35,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/realmayus/youmatter/issues"
# If the mods defined in this file should show as seperate resource packs
showAsResourcePack=false
license="MIT License"

[[mods]]
  modId="youmatter"
  version="${version}"
  displayName="YouMatter"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/youmatter"
  credits="Thanks to Hailtothebreak and bl4ckscor3 for the 1.16.1 and 1.16.4 ports respectively!"
  authors="realmayus"
  description='''
  A mod that allows you to duplicate items using U-Matter, an expensive fluid that can be obtained using machines by consuming energy.
  '''

  [[dependencies.youmatter]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.youmatter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"